### ISSUE TITLE
scripts buffer can't be sorted

### ISSUE THREAD

**Issue by github-cygwin** [de-vri-es/weechat-autosort#12]
I'd like to sort the "scripts" buffer to the top, right after core and fset buffer.
But for some reason it doesn't work.  My ruleset is

0: core = 0
1: fset = 1
2: scripts = 2
3: irc.server = 3
4: irc = 4
5: * = 5

However, the scripts buffer is always sorted at the end of the list.  I tried changing
that to

2: \*scripts\* = 2

but to no avail.  What am I doing wrong?

Thanks,
Corinna

**Comment by de-vri-es** [comment]
Hey,

It looks like you're still using 2.x. It would recommend updating to the latest version, which has a different sorting rule system.

Either way, the problem here is that script buffers generally don't have `scripts` in the name anyway. They're generally called `python.$name` or `perl.$name`.

So if you replace `scripts = 2` with two rules: `python = 2` and `perl = 2` you should be closer to what you want.  Version 2.x always sorts on full buffer name after the rules were applied though, so the perl buffers will always be sorted before python buffers, unless you also add a replacement rule to strip the prefix.

The new system in version `3.x` is much more flexible. But you will need to manually migrate your rules to the new system if you do update.

**Comment by github-cygwin** [comment]
What I was talking about was not the window of some script, but the window of the
script extension you open with "/script".  Whatever I try, this window is always appended
to the end of the list.

Sorry, but the 3.x syntax is much to convoluted for my taste, so I stick to 2.8 for the time
being

Or can you show me how to express the above in 3.x syntax?


Thanks,
Corinna

**Comment by de-vri-es** [comment]
Ah, my bad, that makes sense.

That buffer is called `script.scripts` though, so with the old rules system you would have to write `script = 2` instead of `scripts = 2`.

To be honest, I'm not entirely sure what your 2.8 rules do, since replacement patterns and the `group_irc` option also influence the result.

But, with the new rules, this should sort the core buffer first, followed by fset, scripts, then IRC and the rest last. It also sorts IRC buffers in a tree-like view:
```php
0: ${core_first}
1: ${if:${buffer.full_name}!=fset.fset}
2: ${if:${buffer.full_name}!=script.scripts}
3: ${irc_first}
4: ${irc_raw_first}
5: ${if:${plugin}==irc?${server}}
6: ${if:${plugin}==irc?${info:autosort_order,${type},server,*,channel,private}}
7: ${if:${plugin}==irc?${hashless_name}}
8: ${buffer.full_name}
```

If instead you want all IRC server buffers at the top, followed by the channels/private buffers per server:
```php
0: ${core_first}
1: ${if:${buffer.full_name}!=fset.fset}
2: ${if:${buffer.full_name}!=script.scripts}
3: ${irc_first}
4: ${irc_raw_first}
5: ${if:${plugin}==irc?${if:${type}!=server}}
6: ${if:${plugin}==irc?${server}}
7: ${if:${plugin}==irc?${info:autosort_order,${type},*,channel,private}}
8: ${if:${plugin}==irc?${hashless_name}}
9: ${buffer.full_name}
```

You can tweak them further of course, depending on what you want to do with channel names containing `##` and if you want private buffers and channels mixed or not. I can assist on freenode as well. My nickname there is `de-vri-es`.

**Comment by de-vri-es** [comment]
As discussed on freenode, the issue is resolved using the new 3.x rules.
