### ISSUE TITLE
Issues with custom sort when Slack channels are involved

### ISSUE THREAD

**Issue by Strykar** [de-vri-es/weechat-autosort#20]
`autosort.py` defaults works fine with Slack teams and channels.

But if I wish to sort my IRC servers like..
`/autosort rules update 4 ${if:${plugin}==irc?${info:autosort_order,${server},bitlbee,lair,freenode,oftc,efnet,*}}`
..all the Slack channels show up under the last Slack team.

See https://i.imgur.com/NwBc3Nc.png

I can fix this with another rule like:
`/autosort rules update 5 ${script_or_plugin}==slack?${info:autosort_order,${server},googlecloud-community.slack.com,openobservatory.slack.com}` 

Perhaps I'm misreading the changelog or is this a bug?
```
3.7:
 * Make default rules work with bitlbee, matrix and slack.
```

**Comment by pascalpoitras** [comment]
this is normal because autosort_order return a number, and all servers not specified will have the same number.

for example try this

`/eval -n ${info:autosort_order,friend,hi,how,are,you,*} `

will return 5

`/eval -n ${info:autosort_order,brother,hi,how,are,you,*}`

also return 5.

also you check for ${if:plugin}==irc so slack buffer will have an empty string. Here is one way you can fix that

```
/unset autosort.v3.rules
/autosort rules update 4 ${info:autosort_order,${server},bitlbee,lair,freenode,oftc,efnet,*}
/autosort rules insert 5 ${server}
```

**Comment by de-vri-es** [comment]
Indeed, as @pascalpoitras says, what you're seeing is expected behavior. And indeed, inserting a new rule rather than replacing the default one will usually work better. That way there is always a sort order defined for all servers, even if you don't list them specifically in your own rule.

@Strykar: Does this resolve your issue?

**Comment by Strykar** [comment]
Yes it does, thank you @pascalpoitras and @de-vri-es for clearing that up.
Closing.

**Comment by de-vri-es** [comment]
Glad to hear :)
